# Generated by Django 3.1.3 on 2020-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_completion', models.DateField(verbose_name='Дата выполнения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
