# Generated by Django 3.1.3 on 2020-11-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус выполнения'),
        ),
    ]
