# Generated by Django 3.1.3 on 2020-11-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201104_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус выполнения'),
        ),
    ]
